# Generated by Django 3.0 on 2023-01-03 17:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEmployers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title of your resume')),
                ('first_name', models.CharField(max_length=20, verbose_name='Your first name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Your last name')),
                ('resume', models.TextField(verbose_name='Your resume')),
                ('comment', models.TextField(blank=True, verbose_name='Information')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Your number phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Your email')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title of your vacancy')),
                ('first_name', models.CharField(max_length=20, verbose_name='Your first name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Your last name')),
                ('vacancy', models.TextField(verbose_name='Your vacancy')),
                ('comment', models.TextField(blank=True, verbose_name='Information')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Your number phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Your email')),
            ],
        ),
    ]
